function [a] = choiceList(headline,instraction,listOfChoice)
list = listOfChoice;
a = listdlg('PromptString',{instraction,''},...
    'Name',headline,...
    'SelectionMode','single','ListString',list);
