function [YearlySumCalc] = YearlySumCalc(EmissionsByYearsBAU)
YearlySumCalc = array2table(zeros(1, width(EmissionsByYearsBAU)));
for i = 1:width(EmissionsByYearsBAU)
    Electricity = EmissionsByYearsBAU{2,i}{1,1}{7,9}+...
    sum(EmissionsByYearsBAU{3,i}{1,1}{:,7});
    Transportation = sum(EmissionsByYearsBAU{4,i}{1,1}{:,16})+...
    sum(EmissionsByYearsBAU{5,i}{1,1}{:,12}) + sum(EmissionsByYearsBAU{6,i}{1,1}{:,7});
    Food = sum(EmissionsByYearsBAU{1,i}{1,1}{1,:});
    Construction = sum(EmissionsByYearsBAU{7,i}{1,1}{:,2});
    YearlySumCalc{1,i} = (sum(EmissionsByYearsBAU{1,i}{1,1}{1,:})+...
    EmissionsByYearsBAU{2,i}{1,1}{7,9}+...
    sum(EmissionsByYearsBAU{3,i}{1,1}{:,7})+...
    sum(EmissionsByYearsBAU{4,i}{1,1}{:,16})+...
    sum(EmissionsByYearsBAU{5,i}{1,1}{:,12})+...
    sum(EmissionsByYearsBAU{6,i}{1,1}{:,7})+...
    sum(EmissionsByYearsBAU{7,i}{1,1}{11:13,2})+...
    EmissionsByYearsBAU{10,i}{1,1}{1,2})/1000000;
end

ColumnNames = ones(1,width(EmissionsByYearsBAU));
for i = 1:width(ColumnNames)
    ColumnNames(i) = 2016+i;
end
ColumnNames = string(ColumnNames);
YearlySumCalc.Properties.VariableNames = ColumnNames;
end

